name: Gradle Release

on:
  workflow_call:
    secrets:
      PACKAGES_RW_ACTOR:
        required: true
      PACKAGES_RW_TOKEN:
        required: true

jobs:
  build-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-tags: "true"
          fetch-depth: "0"

      - name: Set up JDK
        uses: actions/setup-java@v6
        with:
          java-version: "25"
          distribution: "zulu"
          cache: 'gradle'

      - name: Publish with Gradle
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "nobody@fk.se"
          ./gradlew updateVersion && ./gradlew release
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PACKAGES_RW_ACTOR: ${{ secrets.PACKAGES_RW_ACTOR }}
          PACKAGES_RW_TOKEN: ${{ secrets.PACKAGES_RW_TOKEN }}
