name: NPM PKG Lint

on: [workflow_call]

permissions:
  contents: read

jobs:
  npm-pkg-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Use Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24.x
          cache: "npm"
      - name: Install Dependencies
        run: npm ci
      - name: npm-pkg-lint
        uses: ext/npm-pkg-lint@master
        with:
          folders: packages/*
          allow-dependencies: "@fkui/user-lib-design"
